### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by dimobelov** [pytesNET/snicker#1] opened 2019-03-11 11:33 UTC
I tested latest version and all looking good so far. I have some ideas:
1. Change file structure. Keep comments for each page in own database including comment body(now you create file for body). If we have site with 1k pages and 100 comments per page with current database per site all will go wrong.
2. Maybe is good to keep database in own place. Every plugin have own directory in Bludit ( `$this->workspace()` ).

And thank you. Going to have good comments for Bludit.

**Comment by SamBrishes** [comment] 2019-03-11 12:14
Hellow,

thanks for testing and your ideas.

1. So you mean "one comment database file" per content page?
2. Good idea, I will change this!

Sincerely,
Sam.

**Comment by dimobelov** [comment] 2019-03-11 13:11
Yea, now you have one comments.php that keep comments from all pages, right? My idea is in this file keep only page slugs that have comments and some general info, and each page to have its own comments.php that keep only its own comments.

**Comment by SamBrishes** [comment] 2019-03-11 14:04
Yeah, that's maybe way better for big blogs / many posts. I'll change that too.

Thanks.

**Comment by Joduai** [comment] 2019-03-11 19:12
Ohh just found the new push, and comments started to work (checked couple days ago).
So far looking good B)
I've noticed you already separated comments per post.

Got couple things on dashboard after first glimpse:
1. For now comment form lacks user name, and email addres even when "eMail Subscription" option is enabled.
Is it still under development?
Even if it's a bug, optional username field with disabled notification imo should be present.

2. pagination is present with less comments than set in options

3. comments are available for static pages. This should be an option. By default comments should be available only for published posts type. I think stickied posts too, as it's a more of a subtype of published.

4. will there be (or are there already?) notifications about new comments for admin? Email is a default way, but maybe additional options, including social media if set in admin profile (or all users with admin privileges).  

5. showing in form a small notice that basic markup is available (optionally) would be great

6. seems that form and comments phrases are hardcoded in english. Single file translations will be possible in future?

7. Great that there are couple types of comments. One additional would come in handy "newest comments" tab. With disabled moderation comments shown in this tab would be quite easy to moderate.

8. how about handling duplicates? Great that some kind of a token expires with time, but after refreshing page I'm able to post a comment with identical content.

9. captcha? With both external, and internal methods. Explainable by itself ;)
Or maybe internal methods are sufficient to prevent automated spam?


geezz the problems appear gradually when I start to think about possible features and their cons. 5 yrs ago I wouldn't think that a "simple" comment system needs so many restrictions.

**Comment by SamBrishes** [comment] 2019-03-12 08:07
Hellow,

the develop branch gets updated really often, but it's highly recommend to deactivate the Snicker plugin before updating it.

Currently, just the comment body gets stored separately, but as @dimobelov already pointed out: We want to store all comments (+ the comment bodies) / content page. So each content page receives it's own `comments` file. This should be also the best solution.

1. The username and eMail address should already be shown up (but ONLY if you're not logged in). Logged in users gets stored a bit differently in the comments database (The eMail address will be fetched from the users database, so the respective user can update his eMail, without to think about his comments :D).

2. The listing of the comments gets completely changed, I hope this will fix this issue too :3 

3. Thanks, I will implement an additional option, where the user can configure where the comments should be available. (Currently the comments are shown everywhere, unless the `allowComments` option on the page is set to `false`)

4. Currently, the only available notification is the small badge on the menu item. The subscription / eMail function isn't written yet, but is in planing. A dashboard widget should be possible, but at the moment there will be no handler for any social media plattform.

5. Jup, that's true. I will add respective notices.

6. It's just the development build, which is currently hardcoded in english. It will be translatable, of course.

7. I'm not really sure, what you mean. The "Pending" tab shows comments (which must be moderated) only, and the "Public" tab shows all comments, which has been already moderated (starting with the newest comments).

8. I'll check that, but sounds good.

9. Supporting reCaptcha is also in planing, but I'll try to embed an internal solution too.

10. I'll try to manipulate the deactivation of the plugin. I guess a simple question like "Do you want to delete all comments too?" should be solve this issue. 

Thanks, I also didn't think that you have to pay so much attention here. And a internal captcha solution is not much work, but I guess really important in (spam) times like this.

Thanks for your suggestions and improvements.

Sincerely,
Sam.

**Comment by Joduai** [comment] 2019-03-12 10:18
> We want to store all comments (+ the comment bodies) / content page. So each content page receives it's own `comments` file. This should be also the best solution.

I've looked at the structure, and everything looks clear with changes you made after @dimobelov suggestions. My question is if every comment is going to be stored as a standalone file in post/comments directory as it is now? Or will all comments bodies "somehow" be stored or cached in a single db file per  page just for performance sake? Small blog with couple comments won't even notice the difference, but what if somebody having quite much contents starts getting serious amount if responses?

1. I tried as many use cases as possible. Form shown for a guest user contains only title and message body + two checkboxes: agreement, and Subscribe via eMail - which doesn't do anything after checking it.  
![defaultform](https://user-images.githubusercontent.com/4009106/54191245-d5e78500-44b5-11e9-8a9a-0bb1ad19bd83.png)


> (Currently the comments are shown everywhere, unless the allowComments option on the page is set to false)

This is quite odd to me. I've seen that pagesDB contains `"allowComments": true,` in every page entry. But I didn't find any checkbox in page's options for comments. Does it appear  only with enabled disqus plugin?

> I'm not really sure, what you mean. The "Pending" tab shows comments (which must be moderated) only, and the "Public" tab shows all comments, which has been already moderated (starting with the newest comments).

7. I have cut the message unfortunately so my idea wasn't described clearly.
When I disable moderation so that the comments appear right away I'd like to have a possibility to see a list of latest, unread comments. I thought that an additional tab could list them. But now when I think of it, would it be possible to mark somehow new comments in public list? With an additional button "mark all comments as read" ?

btw. just imagined replying to couple comments from within backend. Wouldn't make it easier for site/blog maintainer to "bulk" reply to comments right on comments admin page? More of an idea for future.

-----

Got a question about spam. What method do you use to mark a comment as spam?
Do you base on recognizing only strings like links containing http/www or some sort of specific words?
I didn't look at the code yet.

**Comment by SamBrishes** [comment] 2019-03-13 06:28
Hellow,

It isn't changed yet, but all comment bodies gets stored in a single database file. The database file will also be stored minified, at least if the debug mode is disabled in bludit. I'm really not into chaching and chache-systems, but I'll check them if it would help / speed up the plugin in any way.

1. That's really weird. Did you get an error message, when trying to submit a comment (when you arn't logged in)? Which theme do you use?

> This is quite odd to me. I've seen that pagesDB contains "allowComments": true, in every page entry. But I didn't find any checkbox in page's options for comments. Does it appear only with enabled disqus plugin?

That's a good question. I can't find it either. I'll check Bludits source code, or ask @dignajar for any information about that.

7. Oh, now I understand. That should be possible, I'll check them out and look for a solution, but I guess just a new tab and a small new true/false field should be the best way to handle this.

That's a good feature for a further version, thanks :3 

-----

Currently, there is no Spam solution implemented yet, and I don't have any either. The admin has the possibility to mark a comment as spam, which shows the respective comment on this tab. Currently it doesn't have any affect, but in the further version it may blocks the hashed IP value (or maybe also the eMail address), but I guess that doesn't help anyway.

Sincerely
Sam,

**Comment by Joduai** [comment] 2019-03-13 19:21
When all the comments are going to be stored in a single DB file for every page, no caching is needed. That explains whole thing. I just thought about physically searching one cursed comments thorugh all the files with random names.

------

For the nick and email fields for a guest visitor I'm a bit confused, and Don't exactly know what was the main cause. I didn't get any php errors nor notices. So I disabled all caching options for apache, cleaned everything including cookies, disabled plugins, switched between default two themes, and fields popped up. I cannot reproduce this behaviour, so I suppose it had something to do with caching.
Consider this as non existing.

------

For the allowComments variable, it's set by default in pages.class for all pages ('allowComments'=>true) and there's no method of controlling it. Either you would need to make a hook for pages options to control this by a checkbox. But since it's a core option, this is an issue of bludit, and other plugin/theme developers could benefit from it.

-------

Tagging unread comments as read/unread would be great. Also automatically marking comments as  possible spam could benefit from this. Those marked as possible spam could have either different flag or color or tag from those manually set as spam comments. Any solution is going to be good. 
The first thing I'd shot for would be to mark as possible spam all contents having a link. Second thing would be some kind of a list with banned words or phrases.  But thats a thing for future, if you won't have any other ideas for adding +0.0.1 to plugin version ;)

--------

Don't know if it's a possible bug, but surely is an unexpected behaviour. While I was searching for the reason that username&email fields for guest users were not generated I noticed that form is parsed after the breadcrumbs plugin I set to be shown in Theme::plugins('pageEnd');
I'm sure I've found somewhere a request for a way to change plugin parsing order, but from what I remember the plugins are parsed in alphabetical order.

**Comment by SamBrishes** [comment] 2019-03-15 18:14
Hellow,

sorry, I was really busy the last days.

### Username and eMail Fields are missing
I don't like bugs, which disappear without any reason, but I hope this issue just stay away for now. D:

### The `allowComments` Variable
I opened a respective [Issue on Bludits Repository](https://github.com/bludit/bludit/issues/993) to add a "Allow" / "Disallow" option field. Regardless of the answer I'll add a temporarily `<select>` field to the single pages, using some "JavaScript Magic".

### Spam / Blacklist function
That's a good idea, and perfect for future releases. :D 

### Plugin Order
I don't know If I'm able to change the plugin order using any method or function. Which Breadcumb plugin do you use? Maybe I can "play" a unsupported solution.

Sincerely,
Sam.

**Comment by Joduai** [comment] 2019-03-15 19:50
Hey, take your time. You're on holidays! 

In the meantime I've left error reporting on on to see if any errors pops up with next RC version. Hopefully I haven't noticed any warnings or notices caused by anything else.
-----
I was recently browsing gh and read the issue you started.  I'm still a but astonished why there was no method to control the comments. Especially when bludit comes by default with disqus plugin made also by @dignajar  I suppose that there were too many small things on todo list, and along with new issues makes it hard to maintain everything on daily basis.
Anyway, have on mind that the _javacadabrascript_ solution you are implementing needs to be there anyway for those older installations that won't be updated. But I suppose that the need of having a nice commenting system will force users to update.
-----
As it goes to the order of plugins, you can download breadcrumbs from
https://gumroad.com/makeitblu
Just set them to be shown at the page end.
To be honest this is another issue of bludit, as the lack of a way to set plugins order has already been pointed out. Especially when it goes to plugins outputs in sidebar.
In my case I'll either go with setting the breadcrumbs to be parsed at the beginning of page or change comments directory name and add a digit. prefix. Assuming that there's no hardcoded path to any asset or include.

**Comment by SamBrishes** [comment] 2019-03-15 20:31
Hellow,

I don't try to be on holidays.

Maybe the `allowComments` option was a preparation of a "coming" core plugin, as discussed [here](https://github.com/bludit/bludit/issues/685). However, the small JavaScript snippet I'm using for this isn't really big, so it is no problem to keep it for older versions (in case a core implementation will be done).

```php
?>
<script type="text/javascript">
    (function(){
        "use strict";
        var w = window, d = window.document;

        // Render Field
        var HANDLE_COMMENTS_FIELD = '<?php echo Bootstrap::formSelectBlock(array(
            'name'      => 'allowComments',
            'label'     => $L->g('Page Comments'),
            'selected'  => (!$page)? '1': ($page->allowComments()? '1': '0'),
            'class'     => '',
            'options'   => array(
                "1"         => $L->g('Allow Comments'),
                "0"         => $L->g('Disallow Comments')
            )
        )); ?>';

        // Ready ?
        d.addEventListener("DOMContentLoaded", function(){
            if(d.querySelector("#jscategory")){
                var form = d.querySelector("#jscategory").parentElement;
                form.insertAdjacentHTML("afterend", HANDLE_COMMENTS_FIELD);
            }
        });
    }());
</script>
```

-----

Thanks, I buyed the plugin and will test it, maybe I found another solution.

Sincerely,
Sam.

**Comment by Joduai** [comment] 2019-03-24 03:45
One additional feature I forgot to mention: option to disable comments.
Either per post, globally (for temporary purposes, like going on holidays, or for an ongoing migration process) or maybe even a time based allowance to comment (for example posts older than half a year can become obsolete, and there's already a new, updated content).

**Comment by SamBrishes** [comment] 2019-03-24 07:28
Hellow,

sounds good. At the moment it is already possible to disable the comments per each single page. The first version will also allow you to restrict the comments to the page / content type. But an globally / temporary possibility can be added in further releases too.

Sincerely,
Sam.

**Comment by SamBrishes** [comment] 2019-03-29 12:14
Hellow and sorry for the long wait,

A new update has been released, which adds the new DB structure: one `comments.php` / content page + an general indexing file. It isn't finished yet, it may cause some issues, but it should work. 

If you want to test it please don't forget to **uninstall** the current version, before you update to the new one! That's really important.

Changes:
- New _GET / _POST array structure
- Admin pages splitted into multiple files
- A new admin page for nit-logged-in users
- Improved Admin design and JavaScript files
- New shortfunction
- New DB structure
- New comments indexing (one comments.php file per content page)
- New comments user indexing
- New Snicker Handler class 
- Almost all strings are translatable using the S18N system
- A few changed / improvements
- A few other stuff...

Hohoho. Thanks for testing-

Sincerely,
Sam.

**Comment by Joduai** [comment] 2019-03-29 20:51
Checked current version, and below my thoughts:

1. A lot of configuration string sits in source files. You mention that all strings are translatable, but I couldn't get them translated in .json file. Is this possible or strings inside sn_e("") function aren't  processed in current version?

2. With disabled option: allow comments on static pages notification  "The comment section on this page has been disabled!" is still being shown.
Imo this note should be shown only on selected types of pages, and only as an option.

3. Terms of Use Checkbox - should also offer an input field to enter own text in admin area.

4. I found out why I hadn't see the username and email fields in earlier version.
   You use semantically wrong html tags in form. <header> and <footer> tags are supposed to be used once in website's source. That's why those one got styles from theme css, and along with js methods binded to them, were completely out of spectrum.
   Check attached file, I made simplest hotfix while writing this. 
 
[custom.zip](https://github.com/pytesNET/snicker/files/3024489/custom.zip)

5. Got a long list of warnings and notices on comments admin page, beginning with
   
```
    Warning: Illegal string offset 'status' in /bl-plugins/comments/system/class.comments-index.php on line 58
    Notice: Uninitialized string offset: 0 in /bl-plugins/comments/system/class.comments-index.php on line 58
```
    
6. when using classic post method  (ajax disabled) there could be a notice hooked into pagebegin() so that user would see the status of his message after page reloads.

7. didn't check if you set any email validation, but error message should be split between username and email (used wrong email string on purpose)
> "An error occured: The Username or the eMail address is missing!"

8. while on notifications topic, with enabled moderation, user should get more informative default notice despite: "Thanks for your comment!" He won't know that comment is under moderation, and I suppose he will try to resend the comment again, and again.
An additional condition with "snicker-success-X" message should do it.

9. an excerpt of comment message in admin would be nice to see. More than one comment titles might be identical, and without the title, only " No Comment Title available " message is shown. I need to edit comment to see its content.
  Maybe an ajax popup containing comment content would be great.

10. I'm still fascinated with the gravatar usage.
    I can't remind myself when I saw for the last time user's true gravatar image in comments :)
    Thus showing avatars should be optional. From the other hand gravatar offers couple generators and this would be nice to have this option enabled, as it offers identicon among the others ( also monsterid,wavatar,retro, robohash).
    Also a standalone identicon.net jscript could be used. As a last sort I'd use css to take initials from username and style them.
    
11. comment form should be also available to render at the bottom of comments list

12. How will future updates work? I mean how the data is going to be backuped? As we know, disabling plugins delete their dirs in /workplaces along with stored settings in /databases/plugins.
 
Uhh, pretty much after a short rendez vois with this version.

----- 

btw. could you shred some light about
>A new admin page for nit-logged-in users
I'm not sure where to look for it as a visitor.

**Comment by SamBrishes** [comment] 2019-03-30 06:17
Hellow thanks for testing.

1. That is my mistake, I should have written that "almost all Strings are prepared for translation".

2. Fixed, the option (or string message) will be added soon.

3. Added a new Field under "Strings" and adapted the stucture

4. [As discussed here on StackOverflow](https://stackoverflow.com/questions/4837269/html5-using-header-or-footer-tag-twice) there is no restriction to use this HTML elements just once per document. It should also be semantically correct, as it gets rendered within an own '<section>' element. However, I changed this to your solution! And thanks for working out a Hotfix, I really appreciate your help!

5. That shouldn't happen. Have you uninstalled the plugin before installing / updating to the new one?

6. Another message? Because the user already receives one on the comment form section.

7. There is an eMail validation on the respective User Indexing. And yes, I'll split this messages.

8. First: Yes an own Success message would be better. Second: In future updates the comment, which is under moderation, should also be shown to the author (and only to the respective author) with an respective info message.

9. Yes, that was also planned of course. There will also be a button, which loads and shows the full comment content within a popup. (So the admin doesn't need to switch to the edit screen to read it).

10. I was a WordPress Plugin Developer, so I couldn't get of from gravatars. ^^ But yes, this function will also be configurable, currently it is just a small "dropin" function within the Snicker_Template. And the `identicon.net` script may gets used too, I'll check it out.

11. That's true, it is on my list!

12. That's a good question, I have no idea right now. :D 

-----

I have no idea what this means, I was pretty tired when I wrote that.

-----

Thanks for your time and suggestions!

**Comment by Joduai** [comment] 2019-03-30 13:16
4. All this html5 is still a minefield, and every discussion I saw is about dang semantics. 
Of course there can be multiple headings, footers and other html5 tags, but all lies in their content. 

Anyway using them for generating a form is just semantically wrong in this case. But if you stay with them you should use at least Id's to mark those containers. Like I mentioned earlier, page's default header and footer are existing by default in every html5 theme, have their own css defined by main tag, and might be targeted with js only by tag. This makes everything challenging .

5. yes, I've disabled earlier version, and completely deleted files before uploading new ver.
I think the problem lies in php version. I've got v7.2 set on webhosting. 
$this->db contains initial, empty values in getPending(), and this might cause the warnings and notices when using strings in arrays with php > 7.1. I tried with array_slice($this->db, 1) to omit 1st rwo in the loop, but that would be too easy...
Nonetheless function works, but no idea how it behaves in future php versions.

6. Well, the success/error message within form is a must have of course. I'm talking more from my own experience point of view with using forms on crappy websites (most of which are based on wordpress ... ehh). I rarely get any response after clicking "send" button. The more, I need to search for a response message assuming I did get such thing. It is sometimes rendered without any stylings, and while inheriting css styles might be covered by other containers. So this option could get in handy on long pages or even those having many comments (aside from comments pagination) after page reloads. I'll try to check how it looks like with invoking a message in pagebefore().

8. Great to know. 
btw. are you going to set in visitor's browser a cookie for pending comment?
European law with all this cookie circus got on my nerves long time ago. Along with latest GDPR madness I'd have to inform visitors about setting a cookie >_<

10. Understandable :) 
I had to check to be 100% sure what was the way of generating avatars on blogs I sometimes visit.
Then I realised that gravatar offers dozen fallback solutions by itself with identicon among the others, not only a default "mystery person" ;)
All info on http://en.gravatar.com/site/implement/images/
Standalone identicon js could be used for disabled gravatar functionality for on the fly generated avatars.
But since you already impemented gravatars using 1 additional fallback other than "mystery person" for v1.0 launch would be more than enough.

This already is going to be the most fancy commenting system for flat file cms I've seen ;)

--- 

To be honest I have no idea what sort of backup solution could be used.
If you are able to save the comments.php inside respective /content/pages directories, those should stay no matter if the plugin is disabled or deleted.
Once it's installed/enabled again, comments staying in page directories could be parsed to rebuild comments database.

Maybe a hard way of backuping whole settings and dbs within admin panel? 
Just like bludit's backup plugin does with downloading and restoring backup. But this would need an option to also upload the archive. 
Just a thought that using this method should force a password protection in archived files.

**Comment by SamBrishes** [comment] 2019-03-30 16:38
4. The HTML5 contains has already been removed [with the latest commit](https://github.com/pytesNET/snicker/commit/ca7cdefc15f4c699f40d481052e2a5c07381c4aa).

5. The Pull Request from @ should fix this issue. Thanks.

6. I'll check that.

7. I can also use the _SESSION, so the user will see that his comment is in moderation until he closes the brower.

8. Ui, it is on my todo list ;)

Thanks, that was my hope ;)

-----

I already stored the comments within the content/pages diectories, and switched it to the plugins workspace. I guess a manuel / automatic backup solution should be okay. But I will ask myself this question on the end of the development process again.

**Comment by SamBrishes** [comment] 2019-03-31 05:41
FINALLY... After a long time I was FINALLY able to create a method, which returns the comment sorted by date AND depth (as single-depth array). Okay, that was a lie, it isn't an array at all. I'm using a Generator, which returns the respective comment UIDs. But still... It is finally working!

It also has a view other changes, since my last post 13 hours ago. We are nearing the completion!

**Comment by dimobelov** [comment] 2019-03-31 10:28
Hi, first thanks for your work. Good progress this weekend :) I think it is not bad to allow only one lvl of replay like some other platforms. This will not broke design and readability.

**Comment by SamBrishes** [comment] 2019-03-31 10:59
Hello,

thanks. You can configure the level / depth of commention on your own using the option "Comment Depth". The new default option will be 3 (I recently reduced this level from ∞ to 5). 

Sincerely,
Sam.

**Comment by Joduai** [comment] 2019-03-31 13:46
Looking good 😎 
I can't even imagine a tree with 20 lvl deep replies 😆 
Media queries for mobile will surely have to show max 3 lvls, if not 2, but all depends on site owner.

**Comment by SamBrishes** [comment] 2019-03-31 14:09
Thanks.

Theoretically you could also create a "Thread"-based comment layout / template as used on [the german IT Magazine "heise"](https://www.heise.de/forum/heise-online/News-Kommentare/Urheberrechtsreform-EU-Parlament-winkt-Upload-Filter-und-Leistungsschutzrecht-durch/forum-422805/). This can also show a 50 level depth comment structure without any problems. Just sayin' ;3

**Comment by SamBrishes** [comment] 2019-03-31 20:48
The first alpha version will be published soon, just the following points are missing. Nothing else will be added now, unless it is done really quickly or it is REALLY important. (I mean... It's just the first alpha version... ;P)

- [ ] Comments made by blocked users are directly marked as spam
- [ ] A Spam counter badge
- [ ] Correct redirects + Correct and Recognizable Error / Success messages
- [ ] Warning Message when the plugin gets disabled (Backup Comments before deactivation)

Sincerely,
Sam.

**Comment by SamBrishes** [comment] 2019-04-01 07:46
Version 0.1.0 is out now

**Closed by SamBrishes** 2019-04-01 07:46 UTC
Labels: Request, Topic
